DEPARTMENTS_MAP = {
    "che": "Chemical",
    "che-idd": "Chemical IDD",
    "cer": "Ceramic",
    "cer-idd": "Ceramic IDD",
    "civ": "Civil",
    "civ-idd": "Civil IDD",
    "cse": "Computer Science",
    "cse-idd": "Computer Science IDD",
    "eee": "Electrical",
    "eee-idd": "Electrical IDD",
    "ece": "Electronics",
    "mat": "Mathematics",
    "mat-idd": "Mathematics IDD",
    "mec": "Mechanical",
    "mec-idd": "Mechanical IDD",
    "min": "Mining",
    "min-idd": "Mining IDD",
    "phe": "Pharma",
    "phe-idd": "Pharma IDD",
    "chy": "Chemistry",
    "chy-idd": "Chemistry IDD",
    "met": "Metallurgy",
    "met-idd": "Metallurgy IDD",
    "mst": "Material",
    "mst-idd": "Material IDD",
    "hss": "humanities",
    "phy": "Physics",
    "phy-idd": "Physics IDD",
    "bce": "Biotechnology",
    "bce-idd": "Biotechnology IDD",
    "bme": "Biomedical",
    "bme-idd": "Biomedical IDD",
    "all": "all"
}